const listado = [
  {
    nombre: "Juan",
    apellido: "Perez",
    edad: 25,
    curso: "Full Stack",
    correo: "juan.fullstack@gmail.com",
    sexo: "M",
  },
  {
    nombre: "Ana",
    apellido: "Fernandez",
    edad: 30,
    curso: "Android",
    correo: "ana.fernandez@gmail.com",
    sexo: "F",
  },
  {
    nombre: "Pedro",
    apellido: "Marmol",
    edad: 40,
    curso: "iOS",
    correo: "marmol.pedro@gmail.com",
    sexo: "M",
  },
  {
    nombre: "Susana",
    apellido: "Gimenez",
    edad: 75,
    curso: "iOS",
    correo: "susanagimenez@gmail.com",
    sexo: "F",
  },
  {
    nombre: "Pablo",
    apellido: "Marmol",
    edad: 50,
    curso: "Android",
    correo: "pablo.marmol@gmail.com",
    sexo: "M",
  },

  {
    nombre: "Luisa",
    apellido: "Rojas",
    edad: 28,
    curso: "Full Stack",
    correo: "luisa.rojas@gmail.com",
    sexo: "F",
    hobby: "Enjoys cooking exotic dishes",
    ciudad: "Lisbon",
  },
  {
    nombre: "Diego",
    apellido: "Gomez",
    edad: 32,
    curso: "Data Science",
    correo: "diego.gomez@gmail.com",
    sexo: "M",
    hobby: "Passionate about astronomy",
    ciudad: "Mexico City",
  },
  {
    nombre: "Carmen",
    apellido: "Santos",
    edad: 22,
    curso: "Web Design",
    correo: "carmen.santos@gmail.com",
    sexo: "F",
    hobby: "Creates digital art",
    ciudad: "Miami",
  },
  {
    nombre: "Fernando",
    apellido: "Lopez",
    edad: 35,
    curso: "Android",
    correo: "fernando.lopez@gmail.com",
    sexo: "M",
    hobby: "Plays in a local band",
    ciudad: "Berlin",
  },
  {
    nombre: "Valeria",
    apellido: "Hernandez",
    edad: 26,
    curso: "Data Science",
    correo: "valeria.hernandez@gmail.com",
    sexo: "F",
    hobby: "Enjoys solving puzzles",
    ciudad: "Tokyo",
  },
  {
    nombre: "Ricardo",
    apellido: "Castillo",
    edad: 45,
    curso: "Full Stack",
    correo: "ricardo.castillo@gmail.com",
    sexo: "M",
    hobby: "Collects vintage cars",
    ciudad: "Los Angeles",
  },
  {
    nombre: "Elena",
    apellido: "Vega",
    edad: 29,
    curso: "Web Design",
    correo: "elena.vega@gmail.com",
    sexo: "F",
    hobby: "Practices martial arts",
    ciudad: "Sydney",
  },
  {
    nombre: "Roberto",
    apellido: "Gonzalez",
    edad: 33,
    curso: "iOS",
    correo: "roberto.gonzalez@gmail.com",
    sexo: "M",
    hobby: "Creates short films",
    ciudad: "Cape Town",
  },
  {
    nombre: "Sofia",
    apellido: "Martinez",
    edad: 23,
    curso: "Full Stack",
    correo: "sofia.martinez@gmail.com",
    sexo: "F",
    hobby: "Loves playing video games",
    ciudad: "Seoul",
  },
  {
    nombre: "Hector",
    apellido: "Ramirez",
    edad: 38,
    curso: "Data Science",
    correo: "hector.ramirez@gmail.com",
    sexo: "M",
    hobby: "Enjoys woodworking",
    ciudad: "Vancouver",
  },
  {
    nombre: "Monica",
    apellido: "Soto",
    edad: 27,
    curso: "Web Design",
    correo: "monica.soto@gmail.com",
    sexo: "F",
    hobby: "Passionate about gardening",
    ciudad: "Copenhagen",
  },
  {
    nombre: "Javier",
    apellido: "Herrera",
    edad: 31,
    curso: "iOS",
    correo: "javier.herrera@gmail.com",
    sexo: "M",
    hobby: "Participates in amateur astronomy",
    ciudad: "Amsterdam",
  },
  {
    nombre: "Marina",
    apellido: "Torres",
    edad: 24,
    curso: "Full Stack",
    correo: "marina.torres@gmail.com",
    sexo: "F",
    hobby: "Enjoys scuba diving",
    ciudad: "Auckland",
  },
  {
    nombre: "Carlos",
    apellido: "Ortega",
    edad: 42,
    curso: "Android",
    correo: "carlos.ortega@gmail.com",
    sexo: "M",
    hobby: "Restores classic motorcycles",
    ciudad: "Cairo",
  },
  {
    nombre: "Isabel",
    apellido: "Rios",
    edad: 34,
    curso: "Web Design",
    correo: "isabel.rios@gmail.com",
    sexo: "F",
    hobby: "Volunteers at a local animal shelter",
    ciudad: "Stockholm",
  },
];
